//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public int RoomId { get; set; }
        public string RoomName { get; set; }
        public string RoomCategory { get; set; }
        public int RoomPrice { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public int HotelId { get; set; }
    }
}
